### Register
Post http://localhost:8000/auth/register
Content-Type: application/json

{
    "username": "",
    "password": "",
    "password_confirm": "",
    "email": "",
    "mobile": ""
}

### Login
Post http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "",
    "password": ""
}