###auth

Post http://localhost:8000/auth/register
Content-Type: application/json

{
    "username": "adminam",
    "password": "adminam",
    "email": "adminam@example.com",
    "password_confirm": "adminam",
    "mobile": "09123121212"
}

### lognin
Post http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "adminam",
    "password": "adminam"
}