### Register
Post http://localhost:8000/auth/register
Content-Type: application/json

{
    "username": "inimar",
    "password": "inimar",
    "password_confirm": "inimar",
    "email": "inimar@gmail.com",
    "mobile": "09387631240"
}

### Login
Post http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "inimar",
    "password": "inimar"
}