### Get User Profile

Get http://localhost:8000/user/profile
authorization: {{$dotenv token}}

{
    "username": "",
    "password": ""
}

### Edit User Profile

Post http://localhost:8000/user/profile
authorization: {{$dotenv token}}
Content-Type: application/json

{
    "firstName": "",
    "lastName": "",
    "skills": ["Progamming", "REST Api", "Back-end", "js"]
}